#!/usr/bin/env bash
# cc-fasrc installer — run ONCE on a FASRC LOGIN NODE.
#
#   git clone <this-repo> ~/code/cc-fasrc
#   cd ~/code/cc-fasrc && ./install.sh
#
# Re-runnable (idempotent). After this, `cc-up` starts a sandboxed Claude Code
# in a pinned tmux, and every `cc` / `claude` you launch is sandboxed by default.
set -euo pipefail
REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

# ── 0. Must be a login node (egress + this is where the tmux lives) ──────────
if [ -n "${SLURM_JOB_ID:-}" ]; then
  echo "ERROR: run on a login node, not inside a SLURM job (SLURM_JOB_ID set)."; exit 1
fi

# ── 1. The one writable tree ────────────────────────────────────────────────
SANDBOX="${CC_SANDBOX_DIR:-}"
if [ -z "$SANDBOX" ]; then
  echo "ERROR: set CC_SANDBOX_DIR to your writable project tree (the one dir CC may"
  echo "       write to), e.g.:  CC_SANDBOX_DIR=/n/holylabs/<your_lab>/Users/$USER ./install.sh"
  exit 1
fi
if [ ! -d "$SANDBOX" ]; then
  echo "ERROR: sandbox root '$SANDBOX' does not exist — create it or fix the path."
  exit 1
fi
CCHOME="$SANDBOX/.cc"                       # CC's config/state, kept inside the sandbox
mkdir -p "$CCHOME/.claude" "$SANDBOX/.tmp" "$SANDBOX/.cache"
echo "==> sandbox (writable) root : $SANDBOX"
echo "==> CC config dir           : $CCHOME/.claude"

# ── 2. Toolchain presence (we do NOT install it here — bootstrap is separate) ─
CLAUDE_BIN="$(command -v claude || true)"
if [ -z "$CLAUDE_BIN" ]; then
  echo "WARN: 'claude' not on PATH. Install it once on this account, e.g.:"
  echo "        npm config set prefix ~/.local && npm i -g @anthropic-ai/claude-code"
  echo "      (needs node — 'module load nodejs' or analogen's ~/.local-node)."
  CLAUDE_BIN="claude"
fi
echo "==> claude binary           : $CLAUDE_BIN"

# ── 3. Render settings.json + guard hook into the CC config dir ──────────────
# CC_REMOTE_CONTROL=1 turns on remote control (steer from claude.ai/mobile) at startup.
REMOTE=$([ "${CC_REMOTE_CONTROL:-0}" = "1" ] && echo true || echo false)
sed -e "s#@SANDBOX@#$SANDBOX#g" -e "s#@HOME@#$HOME#g" -e "s#@CCHOME@#$CCHOME#g" -e "s#@REMOTE@#$REMOTE#g" \
    "$REPO_DIR/config/settings.json.tmpl" > "$CCHOME/.claude/settings.json"
sed -e "s#@SANDBOX@#$SANDBOX#g" \
    "$REPO_DIR/hooks/guard-write.py" > "$CCHOME/.claude/guard-write.py"
chmod 0755 "$CCHOME/.claude/guard-write.py"
echo "==> wrote settings.json + guard-write.py"

# ── 4. Pre-seed github host key so CC can git push/pull without prompts ──────
mkdir -p "$CCHOME/.ssh"
if command -v ssh-keyscan >/dev/null 2>&1; then
  ssh-keyscan -t ed25519,rsa github.com 2>/dev/null >> "$CCHOME/.ssh/known_hosts" || true
  sort -u "$CCHOME/.ssh/known_hosts" -o "$CCHOME/.ssh/known_hosts" 2>/dev/null || true
fi

# ── 5. config.env consumed by bin/cc ────────────────────────────────────────
cat > "$REPO_DIR/config.env" <<EOF
# generated by install.sh — edit CC_SANDBOX_DIR to move the writable root.
CC_SANDBOX_DIR="$SANDBOX"
CC_HOME="$CCHOME"
CLAUDE_BIN="$CLAUDE_BIN"
# startup permission mode (CLI flag, overrides settings.json defaultMode):
#   auto (default) | acceptEdits | bypassPermissions | default | plan
# Set CC_MODE=none to drop the flag entirely and let settings.json govern.
CC_MODE="\${CC_MODE:-auto}"
EOF
echo "==> wrote $REPO_DIR/config.env"

# ── 6. Put cc / cc-up on PATH ────────────────────────────────────────────────
mkdir -p "$HOME/.local/bin"
for b in cc cc-up ccd cck cc-doctor cc-iso cc-proxyd cc-approve; do
  ln -sfn "$REPO_DIR/bin/$b" "$HOME/.local/bin/$b"
done
echo "==> linked cc, cc-up, ccd, cck, cc-doctor, cc-iso, cc-proxyd, cc-approve -> ~/.local/bin"

# Slurm submit-proxy queue dirs (used only by Apptainer/iso mode; harmless otherwise)
mkdir -p "$SANDBOX/.cc/slurm-proxy"/{requests,results,processed,approve}

# ── 7. Make sandboxed CC the default in your shells ─────────────────────────
TAG="# cc-fasrc"
for RC in "$HOME/.bashrc" "$HOME/.zshrc"; do
  [ -e "$RC" ] || { [ "$RC" = "$HOME/.bashrc" ] && touch "$RC" || continue; }
  if ! grep -q "$TAG" "$RC" 2>/dev/null; then
    {
      printf '\n%s\n' "$TAG"
      printf 'export PATH="$HOME/.local/bin:$HOME/.local-node/bin:$PATH"\n'
      printf 'alias claude="cc"        # every claude launch is sandboxed to cc-fasrc\n'
    } >> "$RC"
    echo "==> wired PATH + claude->cc alias into $RC"
  fi
done

# ── 8. Optional: store an API key so CC is headless (survives reboots) ───────
if [ ! -f "$CCHOME/.claude/api-key" ] && [ -z "${ANTHROPIC_API_KEY:-}" ]; then
  echo
  echo "NOTE: for unattended/headless auth (no browser login), drop your key at:"
  echo "        umask 077; printf %s 'sk-ant-...' > $CCHOME/.claude/api-key"
  echo "      Or run 'cc' once and complete the OAuth URL by hand (token persists)."
fi

# ── 9. Validate the guard rules end-to-end ──────────────────────────────────
echo
echo "==> guard hook self-test:"
CC_SANDBOX_DIR="$SANDBOX" python3 "$CCHOME/.claude/guard-write.py" --selftest \
  || echo "   WARN: some guard cases failed — run cc-doctor for detail."

echo
echo "=== cc-fasrc installed ==="
echo "Next:"
echo "    cc-doctor        # verify everything on this node (do this first)"
echo "    cc-up            # start/reattach the perpetual sandboxed session"
echo
echo "NOTE: the 'claude'->cc alias applies in NEW shells. In THIS one, type 'cc'"
echo "      (or run: source ~/.bashrc)."
_fqdn="$(hostname -f 2>/dev/null || true)"
case "$_fqdn" in *.rc.fas.harvard.edu) : ;; *) _fqdn="$(hostname -s).rc.fas.harvard.edu" ;; esac
echo "      Reconnect later pinned to THIS login node (bos or holy):"
echo "      ssh ${USER}@${_fqdn}"
